# Generated by Django 5.2.6 on 2025-09-15 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('color', models.CharField(choices=[('#FF6B6B', 'Rouge'), ('#4ECDC4', 'Turquoise'), ('#45B7D1', 'Bleu'), ('#96CEB4', 'Vert'), ('#FFEAA7', 'Jaune'), ('#DDA0DD', 'Violet'), ('#FFB347', 'Orange'), ('#87CEEB', 'Bleu ciel')], default='#45B7D1', max_length=7)),
                ('is_shared', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='folder.folder')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'indexes': [models.Index(fields=['owner', 'name'], name='folder_fold_owner_i_fc0457_idx'), models.Index(fields=['parent'], name='folder_fold_parent__24c90a_idx')],
                'unique_together': {('name', 'parent', 'owner')},
            },
        ),
    ]
