# Generated by Django 5.2.6 on 2025-09-16 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(choices=[('web', 'Site Web'), ('email', 'Email'), ('social', 'Réseau Social'), ('bank', 'Banque'), ('work', 'Travail'), ('personal', 'Personnel'), ('shopping', 'Shopping'), ('entertainment', 'Divertissement'), ('utilities', 'Utilitaires'), ('other', 'Autre')], default='other', max_length=20)),
                ('color', models.CharField(default='#6C757D', max_length=7)),
                ('is_system', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password_encrypted', models.BinaryField()),
                ('url', models.URLField(blank=True)),
                ('notes_encrypted', models.BinaryField(blank=True)),
                ('is_favorite', models.BooleanField(db_index=True, default=False)),
                ('is_shared', models.BooleanField(db_index=True, default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('password_strength', models.PositiveSmallIntegerField(default=0)),
                ('password_changed_at', models.DateTimeField(auto_now_add=True)),
                ('auto_generated', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credential.category')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='folder.folder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='credential.credential')),
            ],
            options={
                'verbose_name': 'Historique Mot de Passe',
                'verbose_name_plural': 'Historiques Mots de Passe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['owner', 'name'], name='credential__owner_i_a63133_idx'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['owner', 'is_favorite'], name='credential__owner_i_a4c344_idx'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['owner', 'folder'], name='credential__owner_i_87be16_idx'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['created_at'], name='credential__created_90e9e0_idx'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['last_used_at'], name='credential__last_us_68404d_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordhistory',
            index=models.Index(fields=['credential', 'created_at'], name='credential__credent_7a01e3_idx'),
        ),
    ]
