# Generated by Django 5.2.6 on 2025-09-15 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('system', 'Système')], default='system', max_length=10)),
                ('auto_lock_timeout', models.PositiveIntegerField(choices=[(0, 'Jamais'), (300, '5 minutes'), (600, '10 minutes'), (1800, '30 minutes'), (3600, '1 heure'), (7200, '2 heures')], default=1800)),
                ('clipboard_clear_timeout', models.PositiveIntegerField(choices=[(10, '10 secondes'), (30, '30 secondes'), (60, '1 minute'), (300, '5 minutes'), (0, 'Jamais')], default=30)),
                ('enable_biometric', models.BooleanField(default=False)),
                ('show_password_strength', models.BooleanField(default=True)),
                ('auto_fill_enabled', models.BooleanField(default=True)),
                ('breach_monitoring', models.BooleanField(default=True)),
                ('login_notifications', models.BooleanField(default=True)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], default='csv', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres Application',
                'verbose_name_plural': 'Paramètres Applications',
            },
        ),
    ]
