# Generated by Django 5.2.6 on 2025-09-16 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credential', '0001_initial'),
        ('folder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.CharField(choices=[('read', 'Lecture'), ('write', 'Écriture'), ('share', 'Partage'), ('admin', 'Administration')], default='read', max_length=10)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='credential.credential')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials_shared', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credential Partagé',
                'verbose_name_plural': 'Credentials Partagés',
                'indexes': [models.Index(fields=['user', 'is_active'], name='sharing_sha_user_id_3e32c6_idx'), models.Index(fields=['credential', 'is_active'], name='sharing_sha_credent_dc7abd_idx'), models.Index(fields=['expires_at'], name='sharing_sha_expires_0d615b_idx')],
                'unique_together': {('credential', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SharedFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.CharField(choices=[('read', 'Lecture'), ('write', 'Écriture'), ('share', 'Partage'), ('admin', 'Administration')], default='read', max_length=10)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='folder.folder')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders_shared', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dossier Partagé',
                'verbose_name_plural': 'Dossiers Partagés',
                'indexes': [models.Index(fields=['user', 'is_active'], name='sharing_sha_user_id_8c4dd4_idx'), models.Index(fields=['folder', 'is_active'], name='sharing_sha_folder__869a7b_idx'), models.Index(fields=['expires_at'], name='sharing_sha_expires_b56a62_idx')],
                'unique_together': {('folder', 'user')},
            },
        ),
    ]
